name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - run: sbt test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: sbt checkAll
