name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        # NOTE(olafurpg) Windows is not enabled because it times out due to reasons I don't understand.
        # os: [windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - run: sbt test
      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: "tests/**/TEST-*.xml"
        if: always()
  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn global add @bazel/bazelisk
      - run: bazel build //... --//semanticdb-javac:enabled=true
      - run: bazel run lsif-semanticdb:bazel -- --sourceroot "$PWD"
      - run: du -h dump.lsif-typed
      - run: bazel build //... --@lsif_java//semanticdb-javac:enabled=true
        working-directory: examples/bazel-example
      - run: bazel run @lsif_java//lsif-semanticdb:bazel -- --sourceroot "$PWD"
        working-directory: examples/bazel-example
      - run: du -h dump.lsif-typed
        working-directory: examples/bazel-example
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: sbt checkAll
