name: Native Image
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        include:
          - os: macOS-latest
            uploaded_filename: lsif-java-x86_64-apple-darwin
            local_path: lsif-java/target/native-image/lsif-java
          - os: ubuntu-latest
            uploaded_filename: lsif-java-x86_64-pc-linux
            local_path: lsif-java/target/native-image/lsif-java
          - os: windows-latest
            uploaded_filename: lsif-java-x86_64-pc-win32.exe
            local_path: lsif-java\target\native-image\lsif-java.exe
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go get github.com/sourcegraph/lsif-semanticdb/cmd/lsif-semanticdb
      - run: git fetch --tags || true
      - name: sbt nativeImage
        shell: bash
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          sbt cli/nativeImage "cli/nativeImageRun --cwd tests/gradle-example"
      - name: sbt nativeImage
        shell: cmd
        if: ${{ matrix.os == 'windows-latest' }}
        run: >-
          "C:\Program Files (x86)\Microsoft Visual
          Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && sbt
          cli/nativeImage
      - uses: actions/upload-artifact@master
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
