name: Sourcegraph
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  scip:
    runs-on: ubuntu-latest
    name: "Upload SCIP"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'sbt'

      - name: Install src
        run: yarn global add @sourcegraph/src

      - name: sbt sourcegraphUpload
        run: sbt sourcegraphUpload

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
